# Generated by Django 2.1.5 on 2019-01-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('utenza', models.CharField(max_length=10, unique=True)),
                ('cellulare', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'utenti',
                'ordering': ['cognome'],
            },
        ),
    ]
