# Generated by Django 2.1.5 on 2019-01-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prestiti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestiti_Allegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, max_length=30, null=True)),
                ('allegato', models.FileField(upload_to='')),
                ('inserito_il', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'allegato',
                'verbose_name_plural': 'allegati',
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10, unique=True)),
                ('seriale', models.CharField(max_length=30, unique=True)),
                ('data_checkin', models.DateField(validators=[prestiti.models.valida_data_checkin])),
                ('data_checkout', models.DateField(blank=True, null=True, validators=[prestiti.models.valida_data_checkout])),
                ('fine_garanzia', models.DateField(blank=True, null=True, validators=[prestiti.models.valida_fine_garanzia])),
                ('os', models.CharField(blank=True, max_length=15, null=True, verbose_name='O.S')),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('disponibile', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'dispositivi',
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Modello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modello', models.CharField(max_length=30, unique=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'modello',
                'verbose_name_plural': 'modelli',
                'ordering': ['modello'],
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Produttore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produttore', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'produttore',
                'verbose_name_plural': 'produttori',
                'ordering': ['produttore'],
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Tipo_Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'tipo dispositivo',
                'verbose_name_plural': 'tipi dispositivo',
                'ordering': ['tipo_dispositivo'],
            },
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio_prestito', models.DateTimeField()),
                ('fine_prestito', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('fk_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Dispositivo', verbose_name='dispositivo')),
                ('fk_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Utente', verbose_name='assegnatario')),
                ('tecnico_consegna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_consegna', to=settings.AUTH_USER_MODEL)),
                ('tecnico_ritiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_ritiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prestito',
                'verbose_name_plural': 'prestiti',
                'ordering': ['inizio_prestito'],
            },
        ),
        migrations.AddField(
            model_name='prestiti_modello',
            name='fk_produttore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Produttore', verbose_name='produttore'),
        ),
        migrations.AddField(
            model_name='prestiti_modello',
            name='fk_tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Tipo_Dispositivo', verbose_name='tipo dispositivo'),
        ),
        migrations.AddField(
            model_name='prestiti_dispositivo',
            name='modello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Modello', verbose_name='modello'),
        ),
        migrations.AddField(
            model_name='prestiti_dispositivo',
            name='produttore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Produttore', verbose_name='produttore'),
        ),
        migrations.AddField(
            model_name='prestiti_dispositivo',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Tipo_Dispositivo', verbose_name='tipo dispositivo'),
        ),
        migrations.AddField(
            model_name='prestiti_allegato',
            name='prestito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestito'),
        ),
    ]
